// message_protocol.js
// UI ↔ Background ↔ Content Script mesajlaşmasını standardize eder.
// GEREKSİNİM: "UI↔CONTENT SCRIPT HABERLEŞMESİNİ chrome.runtime.sendMessage İLE STANDARDİZE ET."

export const MSG = Object.freeze({
  PING: "PING",
  STOP: "STOP",
  PROGRESS: "PROGRESS",

  FIND_THREAD: "FIND_THREAD",
  MANUAL_THREAD_SELECT_START: "MANUAL_THREAD_SELECT_START",
  MANUAL_THREAD_SELECT_CANCEL: "MANUAL_THREAD_SELECT_CANCEL",
  MANUAL_THREAD_SELECTED: "MANUAL_THREAD_SELECTED",

  FETCH_MESSAGES: "FETCH_MESSAGES",
  SEND_MESSAGE: "SEND_MESSAGE",

  SET_MODE: "SET_MODE",
});
